name: Android CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Rust
      run: |
        sudo apt update
        sudo apt install -y curl
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: Grant execute permission for all Gradle Wrappers
      run: |
        chmod +x gradle-plugin/gradlew
        chmod +x gradle-plugin-test/gradlew
        chmod +x sample/java/gradlew
        chmod +x sample/kotlin/gradlew

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Android SDK and NDK
      run: |
        # Install Android SDK
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install the required version of NDK
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;27.1.12297006"

        # Configure local.properties in the sample directory with SDK and NDK paths
        echo "sdk.dir=$ANDROID_SDK_ROOT" > ./sample/java/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" > ./sample/kotlin/local.properties
      env:
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    - name: Publish locally JNI in gradle-rust-plugin directory
      run: |
        cd gradle-plugin
        ./gradlew publishToMavenLocal
        cd ..

    - name: Publish locally gradle-rust-plugin-test directory
      run: |
        cd gradle-plugin-test
        ./gradlew publishToMavenLocal
        cd ..

    - name: Compile Rust JNI Test
      run: |
        cd gradle-plugin-test
        ./gradlew executeTest
